quarkus.grpc.clients.assistant.host=assistant.doc-assistant
quarkus.grpc.clients.assistant.port=80

quarkus.grpc.clients.ingestor.host=docs.doc-assistant
quarkus.grpc.clients.ingestor.port=80
quarkus.grpc.clients.ingestor.plain-text=true

quarkus.http.port=8082

quarkus.oidc-client.auth-server-url=http://keycloak.local/realms/doc-assistant-realm
quarkus.oidc-client.client-id=documentation
quarkus.oidc-client.grant.type=password

quarkus.log.level=WARN
quarkus.banner.enabled=false