# dev
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.chroma.url=http://localhost:8000

# prod
%prod.quarkus.langchain4j.ollama.base-url=http://ollama-service:80
%prod.quarkus.langchain4j.chroma.url=http://chroma-service:8000

quarkus.langchain4j.chroma.collection-name=doc-assistant-data
quarkus.langchain4j.ollama.chat-model.model-id=llama3.2:3b
quarkus.langchain4j.ollama.chat-model.temperature=0.0
quarkus.langchain4j.ollama.embedding-model.model-id=mxbai-embed-large
quarkus.langchain4j.ollama.timeout=120s

quarkus.devservices.enabled=false

quarkus.index-dependency.common.group-id=org.pbhaggblom
quarkus.index-dependency.common.artifact-id=common

quarkus.http.host=0.0.0.0
quarkus.http.port=8080
quarkus.grpc.server.port=9000
