
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=llama3.2:1b
quarkus.devservices.enabled=false

quarkus.index-dependency.common.group-id=org.pbhaggblom
quarkus.index-dependency.common.artifact-id=common