apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chroma
  name: chroma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
      - image: chromadb/chroma:latest
        name: chroma
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: rag-storage
          mountPath: /data
        env:
        - name: PERSIST_DIRECTORY
          value: "/data"
        - name: IS_PERSISTENT
          value: "TRUE"
      volumes:
        - name: rag-storage
          persistentVolumeClaim:
            claimName: chroma-data
