apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
  - host: api.doc-assistant.se
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: assistant-service
            port:
              number: 9000
