# dev
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.chroma.url=http://localhost:8000
rag.location=${RAG_LOCATION_TEST}

# prod
%prod.quarkus.langchain4j.ollama.base-url=http://ollama-service:80
%prod.quarkus.langchain4j.chroma.url=http://chroma-service:8000
%prod.rag.location=/data/rag

quarkus.langchain4j.chroma.collection-name=doc-assistant-data
chroma.tenant=default
chroma.database=default
quarkus.langchain4j.chroma.timeout=60s
quarkus.langchain4j.ollama.embedding-model.model-id=mxbai-embed-large
quarkus.langchain4j.ollama.timeout=120s

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/doc-assistant-realm
quarkus.oidc.client-id=documentation
quarkus.oidc.roles.role-claim-path=resource_access/documentation/roles

quarkus.http.auth.permission.grpc.paths=/ai_assistant.DocumentationService/StartIngestion,/ai_assistant.DocumentationService/ClearDatabase
quarkus.http.auth.permission.grpc.policy=authenticated
quarkus.oidc.token.audience=account
quarkus.oidc.token.issuer=http://keycloak.local/realms/doc-assistant-realm

quarkus.devservices.enabled=false

quarkus.index-dependency.common.group-id=org.pbhaggblom
quarkus.index-dependency.common.artifact-id=common

quarkus.grpc.server.use-separate-server=false
quarkus.http.host=0.0.0.0
quarkus.http.port=8081