quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.timeout=120s
quarkus.langchain4j.chroma.url=http://localhost:8000
rag.location=${RAG_LOCATION_TEST}

quarkus.devservices.enabled=false

quarkus.index-dependency.common.group-id=org.pbhaggblom
quarkus.index-dependency.common.artifact-id=common

quarkus.http.port=8081
quarkus.grpc.server.port=9001